// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity ^0.8.23;

interface IERC20 {
    function balanceOf(address account) external view returns (uint256);

    function transfer(address to, uint256 amount) external returns (bool);

    function approve(address spender, uint256 amount) external returns (bool);
}

interface IJoin {
    function join(address usr, uint wad) external;

    function exit(address usr, uint wad) external;
}

interface ISafeEngine {
    struct CollateralType {
        // Total debt issued for this specific collateral type
        uint256 debtAmount; // [wad]
        // Accumulator for interest accrued on this collateral type
        uint256 accumulatedRate; // [ray]
        // Floor price at which a SAFE is allowed to generate debt
        uint256 safetyPrice; // [ray]
        // Maximum amount of debt that can be generated with this collateral type
        uint256 debtCeiling; // [rad]
        // Minimum amount of debt that must be generated by a SAFE using this collateral
        uint256 debtFloor; // [rad]
        // Price at which a SAFE gets liquidated
        uint256 liquidationPrice; // [ray]
    }

    struct SAFE {
        // Total amount of collateral locked in a SAFE
        uint256 lockedCollateral; // [wad]
        // Total amount of debt generated by a SAFE
        uint256 generatedDebt; // [wad]
    }

    function modifySAFECollateralization(
        bytes32 collateralType,
        address safe,
        address collateralSource,
        address debtDestination,
        int256 deltaCollateral,
        int256 deltaDebt
    ) external;

    function approveSAFEModification(address account) external;

    function safes(bytes32 id, address usr) external view returns (SAFE memory);

    function collateralTypes(
        bytes32 id
    ) external view returns (CollateralType memory);

    function tokenCollateral(
        bytes32 id,
        address usr
    ) external view returns (uint256);

    function coinBalance(
        address usr
    ) external view returns (uint256);
}

interface IOracleRelayer {
    function updateCollateralPrice(bytes32 collateralType) external;

    function redemptionPrice() external returns (uint256);
}

interface ILiquidation {
    function liquidateSAFE(
        bytes32 collateralType,
        address safe
    ) external returns (uint256 auctionId);
}

interface IAuctionHouse {
    function buyCollateral(uint256 id, uint256 wad) external;

    function getCollateralBought(
        uint256 id,
        uint256 wad
    ) external returns (uint256, uint256);
}

interface IRouterV2 {
    function swapExactTokensForTokens(
        uint amountIn,
        uint amountOutMin,
        address[] calldata path,
        address to,
        uint deadline
    ) external returns (uint[] memory amounts);

    function swapTokensForExactTokens(
        uint amountOut,
        uint amountInMax,
        address[] calldata path,
        address to,
        uint deadline
    ) external returns (uint[] memory amounts);
}

interface IRouterV3 {
    struct ExactInputParams {
        bytes path;
        address recipient;
        uint256 deadline;
        uint256 amountIn;
        uint256 amountOutMinimum;
    }

    function exactInput(ExactInputParams calldata params)
        external
        payable
        returns (uint256 amountOut);
}

interface IERC3156FlashBorrower {
    function onFlashLoan(
        address initiator,
        address token,
        uint256 amount,
        uint256 fee,
        bytes calldata data
    ) external returns (bytes32);
}

interface IFlashLoanProvider {
    function flashLoan(
        IERC3156FlashBorrower receiver,
        address token,
        uint256 amount,
        bytes calldata data
    ) external returns (bool);
}

contract Tritium is IERC3156FlashBorrower {
    IERC20 usdc = IERC20(0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48);
    IERC20 weth = IERC20(0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2);
    IERC20 ocean = IERC20(0x967da4048cD07aB37855c090aAF366e4ce1b9F48);
    IJoin colJoin = IJoin(0x13288BD148160f76B37Bea93861cA61BAea120D1);
    IJoin coinJoin = IJoin(0x99665a5252c15cA3E24fcEbAb56d0721fB9D1158);
    ISafeEngine safeEngine =
        ISafeEngine(0x1E6AfA340851D60E75be38494813C09b3356a009);
    ILiquidation liquidation =
        ILiquidation(0x3eFbB71321dB24810E8361a42218dc6e4225e981);
    IAuctionHouse auction =
        IAuctionHouse(0x1fe1a1313B4974909CbBC11b208B9062e0C6666A);
    IERC20 h2o = IERC20(0x0642026E7f0B6cCaC5925b4E7Fa61384250e1701);
    IOracleRelayer oracle =
        IOracleRelayer(0x173d5e2395D0C20d5A3d35d5b7Ec71618211F353);
    IRouterV2 routerV2 = IRouterV2(0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D);
    IRouterV3 routerV3 = IRouterV3(0xE592427A0AEce92De3Edee1F18E0157C05861564);
    IFlashLoanProvider flashLoan = IFlashLoanProvider(0x4EAF187ad4cE325bF6C84070b51c2f7224A51321);
    bytes32 colId =
        0x4f4345414e2d4100000000000000000000000000000000000000000000000000;
    address owner;
    //uint public colOut;
    //uint public coinIn;

    constructor() {
        owner = msg.sender;
    }

    function _getCoin(uint wethToUsdcToH2o, uint ocToH2o) internal returns (uint256) {
        //have ether
        weth.approve(address(routerV3), wethToUsdcToH2o);
        bytes memory path =
            abi.encodePacked(weth, uint24(500), usdc, uint24(500), h2o);
        IRouterV3.ExactInputParams memory params = IRouterV3
            .ExactInputParams({
            path: path,
            recipient: address(this),
            deadline: block.timestamp,
            amountIn: wethToUsdcToH2o,
            amountOutMinimum: 0
        });

        uint h2oOut0 = routerV3.exactInput(params);

        address[] memory pathV2 = new address[](2);
        pathV2[0] = address(weth);
        pathV2[1] = address(ocean);

        weth.approve(address(routerV2), weth.balanceOf(address(this)));
        uint256[] memory amountsOut = routerV2.swapTokensForExactTokens(
            ocToH2o, 
            weth.balanceOf(address(this)),
            pathV2,
            address(this),
            block.timestamp
        );

        uint oceanOut = amountsOut[amountsOut.length-1];

        ocean.approve(address(routerV3), oceanOut);
        path =
            abi.encodePacked(ocean, uint24(3000), h2o);
        params = IRouterV3
            .ExactInputParams({
            path: path,
            recipient: address(this),
            deadline: block.timestamp,
            amountIn: ocToH2o,
            amountOutMinimum: 0
        });
        uint h2oOut1 = routerV3.exactInput(params);


        return h2oOut0 + h2oOut1;
    }

    function _toWeth() internal returns (uint256) {
        ocean.approve(address(routerV2), ocean.balanceOf(address(this)));
        address[] memory pathV2 = new address[](2);
        pathV2[0] = address(ocean);
        pathV2[1] = address(weth);

        uint256[] memory amountsOut = routerV2.swapExactTokensForTokens(
            ocean.balanceOf(address(this)), 
            0,
            pathV2,
            address(this),
            block.timestamp
        );

        return amountsOut[0];
    }

    function onFlashLoan(
        address initiator,
        address token,
        uint256 amount,
        uint256 fee,
        bytes calldata data
    ) external returns (bytes32) {
        fee;
        require(msg.sender == address(flashLoan),"not flashloan");
        require(initiator == address(this), "not this");

        (uint wethToUsdcToH2o, uint ocToH2o, address liquidTarget) = abi.decode(data, (uint256, uint256, address));

        uint coinOut = _getCoin(wethToUsdcToH2o, ocToH2o);

        safeEngine.approveSAFEModification(address(coinJoin));
        safeEngine.approveSAFEModification(address(colJoin));
        safeEngine.approveSAFEModification(address(auction));

        h2o.approve(address(coinJoin), coinOut);
        coinJoin.join(address(this), coinOut);

        uint aucId = liquidation.liquidateSAFE(colId, liquidTarget);

        //(colOut, coinIn) = auction.getCollateralBought(aucId, coinOut);

        auction.buyCollateral(aucId, coinOut);
        colJoin.exit(address(this), safeEngine.tokenCollateral(colId, address(this)));

        _toWeth();

        IERC20(token).approve(address(flashLoan), amount);
        return keccak256('ERC3156FlashBorrower.onFlashLoan');
    }

    function radiate(
        bool updatePrice, 
        uint flashAmount, 
        uint wethToUsdcToH2o, 
        uint ocToH2o,
        uint minOut,
        address target
    ) external {
        require(owner == msg.sender, "not owner");

        if (updatePrice) {
            oracle.updateCollateralPrice(colId);
        }

        flashLoan.flashLoan(this, address(weth), flashAmount, abi.encode(wethToUsdcToH2o, ocToH2o, target));
        
        uint out = weth.balanceOf(address(this));
        require(out >= minOut, "Not enough out");
        weth.transfer(msg.sender, weth.balanceOf(address(this)));
    }

    function rescue(IERC20 token) external {
        require(owner == msg.sender, "not owner");
        token.transfer(owner, token.balanceOf(address(this)));
    }

    function rescueCall(address target, bytes calldata callArg) external {
        require(owner == msg.sender, "not owner");

        (bool success, ) = target.call(callArg);
        require(success, "call failed");
    }
}